##print("Hello World!")
##print("Python can be used for printing")
##print("Each new print statement is printed on a new line!")
##print("We have extra characters that have special meaning too!")
##print("\tbackslash t prints out a tab\twhich is like several spaces")
##print("backslash n\nprints a new line\neach time you type it\n!")

#Q1
print ("R\to\to\tp")

#Q2
print("R\no\no\np")

#Q3
print ("September, 5th, 2026")

#Q4
print ('September, 5th, 2026')

#Q5
print("Sunday\n Monday\n Tuesday\n Wednesday\n Thursday\n Friday\n Saturday\n")

#Q6
print ("1\t2\t3\t4\t5\t6\t7\t8\t
